### ISSUE TITLE
Subquery over CTE

### ISSUE THREAD

**Issue by giuliosmall** [PaddyAlton/DBT-GA4#2]
Hey @PaddyAlton ,

Thanks for opensourcing this ELT exercise - well structured and explained!
One question from my side: could you please explain why in `intermediate_analytics__events_params.sql` you implemented a subquery instead of creating a more readable (and perhaps maintainable) CTE?

I'm sure the result would be the same but, accordingly to your comment `-- subquery allows us to efficiently build this table incrementally` I'm wondering wether you implemented some performance tuning that BQ offers and I'm not aware of.

Thanks.

**Comment by PaddyAlton** [comment]
It's a while since I wrote it, but I remember this was based on doing a lot of 'trial and error' testing with the incremental logic.

I cannot remember exactly how different the built time/amount of data processed was in the two cases, but at least one of them was substantial enough for me to choose the less elegant subquery syntax.

Annoyingly, I could not find a theoretical reason why a subquery would perform better than a CTE. It was surprising to me that it seemed to make a difference. I suspect that it might be something to do with the logic DBT applies when converting the model into a script for an incremental run.

My advice is to try it yourself (do a full build then multiple incremental trials) and see whether there's a difference for you. BigQuery and DBT are constantly evolving (and everyone's data is unique), so it may turn out that it's now irrelevant.

**Comment by giuliosmall** [comment]
Thanks for sharing your feedback @PaddyAlton , much appreciated indeed!
