### ISSUE TITLE
`UNNEST`ing event_params

### ISSUE THREAD

**Issue by giuliosmall** [PaddyAlton/DBT-GA4#3]
In `intermediate_analytics__events_params`, you unnest the `event_params`, each event-parameter pair is turned into a separate row. This operation is standard for flattening nested structures in BQ, allowing to analyze each parameter of an event individually. However, it also means that for events with multiple parameters, the `event_id` will repeat across these rows—one for each parameter.

<img width="824" alt="image" src="https://github.com/PaddyAlton/DBT-GA4/assets/49522377/c1ea66ea-b272-43fd-8892-941f492302e1">

Now, I'm sure I don't have any duplicate `base_analytics__events` and it seems the `LEFT JOIN UNNEST` is triggering the `unique` test defined in `intermediate_analytics__events_params.yml`.

I also understand that on a later intermediate stage in `intermediate_analytics__events_wide_format` you SELECT DISTINCT on the model previously created to avoid duplicates
<img width="689" alt="image" src="https://github.com/PaddyAlton/DBT-GA4/assets/49522377/7a8e39ce-8da4-47cb-8cb6-381158046142">

So my question is, can you really avoid `event_id` duplicates in `intermediate_analytics__events_params` considering the unnesting action?

**Comment by PaddyAlton** [comment]
Ah, good catch - that test shouldn't be there. I have removed it.

The `param_id` surrogate key is the unique key for that model, so we're definitely expecting `param_id` to be unique, but there may be multiple `param_id`s for every `event_id`. That is: the `events_params` model is at the event-parameter grain. The model description is clear about this, so the inclusion of the test must have been a copying error.

By the way, the `SELECT DISTINCT * EXCEPT(param_id)` will not drop these rows with matching event IDs because there is a different `param_key` value for each one. The statement is included because I found that there were sometimes 'true' duplicates, i.e. duplicate events that had come through from GA4 to BigQuery. In retrospect, I think the `EXCEPT(param_id)` is probably unnecessary - I'm fairly sure the param ID will also be duplicated in this case, given the way it's defined.

The intention is that the `PIVOT` statement will then transform the data back to the event grain.
